name: Build MacroPad

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    name: macOS Build
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.8.2'
          host: 'mac'

      - name: Configure
        run: cmake -S software -B build -DCMAKE_PREFIX_PATH=$Qt6_DIR -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Ad-hoc Code Sign
        run: codesign --force --deep --sign - build/MacroPad.app

      - name: Package macOS .app
        run: |
          brew install zip
          zip -r MacroPad-mac.zip build/MacroPad.app

      - name: Upload macOS Build
        uses: actions/upload-artifact@v4
        with:
          name: MacroPad-mac
          path: MacroPad-mac.zip

  build-windows:
    runs-on: windows-latest
    name: Windows Build
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.8.2'
          host: 'windows'
          target: 'desktop'
          arch: 'mingw_64'

      - name: Configure
        run: cmake -S software -B build -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH=%Qt6_DIR% -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Package Windows .exe
        run: |
          $qtBin = "${Env:Qt6_DIR}\bin"
          & "$qtBin\windeployqt.exe" "build\MacroPad.exe"
          Compress-Archive -Path build\* -DestinationPath MacroPad-win.zip

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: MacroPad-win
          path: MacroPad-win.zip
